server:
  port: 9901

eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:9005/eureka
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: Userms
          uri: lb://Userms
          predicates:
            - Path=/user/**
          filters:
            - name: CircuitBreaker
              args:
                name: Userms
                fallbackuri: forword:/Usermsfallback
        - id: Contactms
          uri: lb://Contactms
          predicates:
            - Path=/contact/**
          filters:
            - name: CircuitBreaker
              args:
                name: Contactms
                fallbackuri: forword:/Contactmsfallback

hystrix:
  command:
    fallbackcmd:
      execution:
        isolation:
          thread:
            timeoutInMilleseconds: 5000


management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream
